if: tag IS blank
branches:
  only:
    - master
    - develop

language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules
    - $HOME/.local

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - npm ci

script:
  - echo "No tests ran"

deploy:
  - provider: script
    script: ./scripts/deploy
    skip_cleanup: true
    on:
      branch:
        - master
        - develop
