#!/usr/bin/env bash

# Requires the following environment variables:
# $CONFIG_SECRET_NAME = The name of the AWS secrets manager secret containing the config.

# Bail out on first error.
set -e

# Create AWS dir for credentials and config.
echo "Creating AWS config directory..."
mkdir ~/.aws

# Set AWS CLI credentials.
echo "Setting AWS credentials..."
cat > ~/.aws/credentials << EOF
[default]
aws_access_key_id = $AWS_ACCESS_KEY_ID
aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
EOF

# Set AWS CLI config.
echo "Setting AWS config..."
cat > ~/.aws/config << EOF
[default]
region = $AWS_REGION
output = $AWS_DEFAULT_OUTPUT
EOF

# Download the configuration file.
echo "Downloading deployments configuration file..."
aws secretsmanager get-secret-value \
    --secret-id ${CONFIG_SECRET_NAME} | \
    python -c "import json,sys;obj=json.load(sys.stdin);print obj['SecretString'];" > scripts/config.yml

# Loop through each deployment.
for DEPLOYMENT in $(scripts/parse-config list-deployments -f scripts/config.yml)
do
    # Declare the configuration variables for the deployment.
    echo "Setting deployment configuration for ${DEPLOYMENT}..."
    export AWS_ACCESS_KEY_ID=$(scripts/parse-config get-config -d ${DEPLOYMENT} -k aws-access-key-id -f scripts/config.yml)
    export AWS_SECRET_ACCESS_KEY=$(scripts/parse-config get-config -d ${DEPLOYMENT} -k aws-secret-access-key -f scripts/config.yml)
    export AWS_DEFAULT_REGION=$(scripts/parse-config get-config -d ${DEPLOYMENT} -k aws-default-region -f scripts/config.yml)
    export FRONTEND_ENV_SECRET_ID=$(scripts/parse-config get-config -d ${DEPLOYMENT} -k frontend-env-secret-id -f scripts/config.yml)

    # Get the .env file.
    echo "Downloading .env file..."
    aws secretsmanager get-secret-value \
        --secret-id ${FRONTEND_ENV_SECRET_ID} | \
        python -c "import json,sys;obj=json.load(sys.stdin);print obj['SecretString'];" > .env

    # Build.
    echo "Building..."
    node_modules/.bin/vue-cli-service build --mode staging

    # Deploy to S3.
    echo "Deploying..."
    node_modules/.bin/vue-cli-service s3-deploy --mode staging
done
